// Generated by CoffeeScript 1.7.1

/*
    install.coffee
    cd /apps/bath
    service start
 */

(function() {
  var Service, fs, op, svc, _ref;

  fs = require('fs');

  Service = require("node-windows").Service;

  op = (_ref = process.argv[2]) != null ? _ref : 'start';

  if (op !== 'start' && op !== 'stop') {
    console.log('bad arg:', op);
    return;
  }

  svc = new Service({
    name: "BATH",
    description: "Bathroom Display",
    script: "C:/apps/bath/lib/server.js"
  });

  svc.on("install", function() {
    console.log('BATH Service Installed');
    svc.start();
    console.log('BATH Service Started');
    return console.log("The service exists: ", svc.exists);
  });

  svc.on("uninstall", function() {
    console.log("BATH Service Uninstalled");
    console.log("The service exists: ", svc.exists);
    if (op === 'start') {
      return svc.install();
    }
  });

  if (op === 'stop' && svc.exists) {
    svc.uninstall();
  } else if (op === 'start') {
    svc.install();
  } else {
    console.log('bath already stopped, nothing to do.');
  }

}).call(this);

//# sourceMappingURL=install.map
