// Generated by CoffeeScript 1.7.1

/*
    serve custom web page to show forecast and current pws stats in bathroom display

    cd /bath
    coffee -cmo lib src/srvr.coffee
 */

(function() {
  var body, cacheTime, cheerio, days, div, doctype, fileServer, fileSrvrCum, forecastURL, fs, getForecast, head, html, http, img, lastEmail, mailOptions, nodeStatic, nodemailer, raw, render, request, script, sendWarningEmail, text, title, transporter, url, _ref;

  process.chdir('/apps/bath');

  fs = require('fs');

  url = require('url');

  http = require('http');

  request = require('request');

  cheerio = require('cheerio');

  nodeStatic = require('node-static');

  fileServer = new nodeStatic.Server(null, {
    cache: 0
  });

  fileSrvrCum = new nodeStatic.Server('/', {
    cache: 0
  });

  nodemailer = require("nodemailer");

  transporter = nodemailer.createTransport({
    service: "Gmail",
    auth: {
      user: "mark@hahnca.com",
      pass: "GHJlkjert987"
    }
  });

  mailOptions = {
    from: "mark@hahnca.com",
    to: "mark@hahnca.com",
    subject: "Pill warning",
    text: "Pill warning",
    html: "Pill warning"
  };

  lastEmail = 0;

  sendWarningEmail = function() {
    lastEmail = Date.now();
    return transporter.sendMail(mailOptions, function(error, info) {
      if (error) {
        return console.log(error);
      } else {
        return console.log("Message sent: " + info.response);
      }
    });
  };

  _ref = require('teacup'), render = _ref.render, doctype = _ref.doctype, html = _ref.html, head = _ref.head, title = _ref.title, body = _ref.body, div = _ref.div, img = _ref.img, raw = _ref.raw, text = _ref.text, script = _ref.script;

  setInterval(function() {
    var e, flash;
    if (new Date().getHours() === 5) {
      fs.writeFileSync('flash', 'yes');
    }
    try {
      flash = fs.readFileSync('flash', 'utf8');
    } catch (_error) {
      e = _error;
      flash = 'no';
    }
    if (flash === 'yes' && new Date().getHours() > 10 && (Date.now() - lastEmail) > 60 * 60 * 1000) {
      return sendWarningEmail();
    }
  }, 10 * 60 * 1000);

  cacheTime = 0;

  days = null;

  forecastURL = 'http://api.wunderground.com/api/0ab64c6b7d983f0e/forecast/q/33.840404,-118.186365.json';

  (getForecast = function() {
    if (Date.now() > cacheTime + 10 * 60 * 1000) {
      return request(forecastURL, function(err, resp, data) {
        data = JSON.parse(data);
        days = data.forecast.simpleforecast.forecastday;
        cacheTime = Date.now();
        return console.log('Accessed weather underground and got ' + days.length + ' days.');
      });
    }
  })();

  http.createServer(function(req, res) {
    var dateMS, day, dayIdx, dayOfWeek, dayOfs, e, flash, high, humidity, iconURL, phrase, rain, wind, _i, _len, _ref1;
    console.log('req:', req.url);
    if (req.url === '/') {
      res.writeHead(200, {
        "Content-Type": "text/html"
      });
      res.end(render(function() {
        doctype();
        return html(function() {
          head(function() {
            return title('forecast - bath');
          });
          return body({
            style: 'background-color:black'
          }, function() {
            div({
              style: 'width:100%; height:1375px'
            }, function() {
              div('#forecast', {
                style: 'width:100%; height:45%'
              });
              div({
                style: 'clear:both; float:left; width:100%; height:3px; position: relative; top: 9%; background-color:white; margin-top:-2%;'
              });
              div('#current');
              div({
                style: 'clear:both; float:left; width:100%; height:3px; position: relative; top: 0%; background-color:white; margin-top:-2%;'
              });
              return div(function() {
                div('#dow', {
                  style: 'clear:both; float:left; margin:5% 0 0% 12%; color:white'
                });
                return div('#time', {
                  style: 'float:right; margin:5% 9% 0% 0; color:white;'
                });
              });
            });
            script({
              src: 'http://code.jquery.com/jquery-1.11.0.min.js'
            });
            script({
              src: 'lib/teacup.js'
            });
            return script({
              src: 'lib/script.js'
            });
          });
        });
      }));
      return;
    }
    if (req.url.slice(0, 9) === '/forecast') {
      dayOfs = url.parse(req.url, true).query.dayOfs;
      getForecast();
      if (days) {
        for (dayIdx = _i = 0, _len = days.length; _i < _len; dayIdx = ++_i) {
          day = days[dayIdx];
          if (Date.now() < (day.date.epoch - 3 * 60 * 60) * 1000) {
            break;
          }
        }
        day = days[(dayIdx + dayOfs) % days.length];
        iconURL = day.icon_url;
        high = day.high.fahrenheit;
        phrase = day.conditions;
        rain = day.qpf_allday["in"];
        wind = day.avewind.mph;
        humidity = day.avehumidity;
        dayOfWeek = day.date.weekday;
      } else {
        iconURL = 'http://icons.wxug.com/i/c/k/clear.gif';
        high = 0;
        phrase = '';
        rain = 0;
        wind = 0;
        humidity = 50;
        dayOfWeek = 'Please wait...';
      }
      res.writeHead(200, {
        "Content-Type": "text/json"
      });
      res.end(JSON.stringify({
        iconURL: iconURL,
        high: high,
        phrase: phrase,
        rain: rain,
        wind: wind,
        humidity: humidity,
        dayOfWeek: dayOfWeek
      }));
      return;
    }
    if (req.url.slice(0, 14) === '/cumulus/flash') {
      if (url.parse(req.url, true).query.clear === '1') {
        fs.writeFileSync('flash', 'no');
      }
      try {
        flash = fs.readFileSync('flash', 'utf8');
      } catch (_error) {
        e = _error;
      }
      dateMS = Date.now();
      res.end(JSON.stringify({
        flash: flash,
        dateMS: dateMS
      }));
      return;
    }
    if (req.url.slice(0, 9) === '/cumulus/') {
      req.addListener('end', function() {
        return fileSrvrCum.serve(req, res, function(err) {
          if (err) {
            return console.log('cumulus file server error\n', req.url, err);
          }
        });
      }).resume();
      return;
    }
    if ((_ref1 = req.url) === '/teacup.js' || _ref1 === '/script.js') {
      req.addListener('end', function() {
        return fileServer.serve(req, res, function(err) {
          if (err) {
            return console.log('file server lib error\n', req.url, err);
          }
        });
      }).resume();
      return;
    }
    if (req.url.slice(0, 7) === '/icons/') {
      req.addListener('end', function() {
        return fileServer.serve(req, res, function(err) {
          if (err) {
            return console.log('file server lib error\n', req.url, err);
          }
        });
      }).resume();
      return;
    }
    return req.addListener('end', function() {
      return fileServer.serve(req, res, function(err) {
        var _ref2;
        if (err && ((_ref2 = req.url.slice(-4)) !== '.ico' && _ref2 !== '.map')) {
          return console.log('file server error\n', req.url, err);
        }
      });
    }).resume();
  }).listen(1337);

  console.log('listening on port 1337');


  /*
            tu  we  th
  wund web  85  87  83
  accuwthr  85  85  83
  mywthr2   84  88  84
  google    84  86  86
  weather2  82  89  84
  wthrchan  80  84  82
  wund api  80  83  82
  willywthr 80  82  79
  intlicast 79  85  82
  frcst.io  75  78  79
  wthrbug   75  75  75
  openwthr  70  70  70
   */

}).call(this);

//# sourceMappingURL=server.map
